# Generated by Django 5.2.15 on 2026-07-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_delivery_address_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
